name: deploy-gh-pages
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  run-deploy-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | # setup git, see: https://api.github.com/users/github-actions%5Bbot%5D
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          yarn
          npx gh-pages -d src
